import HeaderLine from './components/HeaderLine'
import SidebarMenu from './components/Menu/SidebarMenu'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Gorilla App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <SidebarMenu />
      <HeaderLine />
      <div className='pb-10'>
        {children}
      </div>
      </body>
    </html>
  )
}
