import HeaderLine from './components/HeaderLine'
import SidebarMenu from './components/Menu/SidebarMenu'
import AdminModalRegister from './components/Modal/AdminModal'
import './globals.css'
import { Inter } from 'next/font/google'
import ToasterProvider from './providers/ToasterProvider'
import { getCurrentUser } from './helpers/getCurrentUser'
import AdminLoginModal from './components/Modal/AdminLoginModal'
import BranchModal from './components/Modal/BranchModal'
import ProductModal from './components/Modal/ProductModal'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Gorila App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body className={inter.className}>
      <ToasterProvider />
      <SidebarMenu />
      <HeaderLine currentUser={currentUser} />
      <AdminModalRegister />
      <AdminLoginModal />
      <BranchModal />
      <ProductModal />
      <div>
        {children}
      </div>
      </body>
    </html>
  )
}